import type { Metadata } from 'next'
import { Arimo } from 'next/font/google'

import './globals.css'

const arimo = Arimo({
  subsets: ['latin'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Spooky Pics',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={arimo.className}>
      <body>{children}</body>
    </html>
  )
}
