import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { Header } from '@/sections/header'
import { stack } from '@styled-system/patterns'
import './globals.css'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Spooky Pics',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body
        className={stack({
          maxWidth: '85.375rem',
          margin: '0 auto',
          minHeight: '100dvh',
          paddingX: 4,
          gap: 0
        })}
      >
        <Header />
        {children}
      </body>
    </html>
  )
}
